### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by rbunn80110** [dgriff777/rl_a3c_pytorch#26]
Slightly baffled by this:

Traceback (most recent call last):
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bob/PycharmProjects/rl_a3c_pytorch-master/train.py", line 31, in train
    player.state = player.env.reset()
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/site-packages/gym/core.py", line 375, in _reset
    observation = self.env.reset()
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/site-packages/gym/core.py", line 123, in reset
    observation = self._reset()
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/site-packages/gym/core.py", line 376, in _reset
    return self._observation(observation)
  File "/home/bob/anaconda3/envs/rl_env/lib/python3.5/site-packages/gym/core.py", line 386, in _observation
    raise NotImplementedError
NotImplementedError

**Comment by rbunn80110** [comment]
Interesting.

pip install gym --upgrade

fixed the problem.
